pub enum Features {
    AuxFan = 1,
    ChamberLight = 2,
    ChamberFan = 3,
    ChamberTemperature = 4,
    CurrentStage = 5,
    PrintLayers = 6,
    Ams = 7,
    ExternalSpool = 8,
    KValue = 9,
    StartTime = 10,
    AmsTemperature = 11,
    CameraRtsp = 13,
    StartTimeGenerated = 14,
    CameraImage = 15,
}
